### ISSUE TITLE
How do I do things like death planes and arrow traps? (Sorry I'm really bad at lua and I cant figure this stuff out)

### ISSUE THREAD

**Issue by beatmakerofficial** [unbelievableflavour/Cotton#33]
Please help i have like 3 days

**Comment by unbelievableflavour** [comment]
@beatmakerofficial hi, sorry I dont have time to explain. Im incredibly busy in real life due to selling my house, getting a morgage and getting a new house. 

But maybe you can try the playdate Discord. We have an official Cotton channel there! Or if you only have 3 days and dont know how to lua, why not make it in pulp?

**Comment by beatmakerofficial** [comment]
I'm trying to make an endless runner, so I can't use pulp, I tried using the platformer demo that I found on the devforum, but it doesn't really work because it doesn't scroll :(
